use_frameworks!

target 'CocoaExpand_Example' do
  pod 'CocoaExpand', :path => '../'

  target 'CocoaExpand_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
